### ISSUE TITLE
"Unsupported quantization type" when quantizing model

### ISSUE THREAD

**Issue by BuilderGuy1** [saharNooby/rwkv.cpp#46]
After successfully converting the RWKV model, quanting it does not work. Here is the error:
``` python rwkv/quantize.py /Volumes/Bantha/_ML/Raven-3B-v11-20230425.bin /Volumes/Bantha/_ML/Raven-3B-v11-20230425_Q5_0.bin Q5_0
Unsupported quantization type 84426624
/Users/dac/Documents/_AI/rwkv.cpp/rwkv.cpp:583: q_type == 2 || q_type == 3 || q_type == 4 || q_type == 5 || q_type == 6
Traceback (most recent call last):
  File "/Users/dac/Documents/_AI/rwkv.cpp/rwkv/quantize.py", line 31, in <module>
    main()
  File "/Users/dac/Documents/_AI/rwkv.cpp/rwkv/quantize.py", line 22, in main
    library.rwkv_quantize_model_file(
  File "/Users/dac/Documents/_AI/rwkv.cpp/rwkv/rwkv_cpp_shared_library.py", line 177, in rwkv_quantize_model_file
    assert self.library.rwkv_quantize_model_file(
AssertionError: rwkv_quantize_model_file failed, check stderr ```

I have tried Q8_0, Q5_0, Q5_1, Q4_2  and all result with the same error.

**Comment by saharNooby** [comment]
Probably, you need to rebuild or re-download the shared library.

For best results, clone the repo from scratch and build it as per instructions in README.

**Comment by BuilderGuy1** [comment]
resolved :-)
