### ISSUE TITLE
Memory error

### ISSUE THREAD

**Issue by dillfrescott** [saharNooby/rwkv.cpp#8]
```
(rwkv) C:\Users\micro\Downloads\rwkv.cpp>python rwkv\chat_with_bot.py C:\Users\micro\Downloads\raven7B_q.bin
Loading 20B tokenizer
System info: AVX = 1 | AVX2 = 1 | AVX512 = 0 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | BLAS = 0 | SSE3 = 1 | VSX = 0 |
Loading RWKV model
ggml_new_tensor_impl: not enough space in the context's memory pool (needed 5589895568, available 5589886801)
Traceback (most recent call last):
  File "C:\Users\micro\Downloads\rwkv.cpp\rwkv\chat_with_bot.py", line 45, in <module>
    model = rwkv_cpp_model.RWKVModel(library, args.model_path)
  File "C:\Users\micro\Downloads\rwkv.cpp\rwkv\rwkv_cpp_model.py", line 37, in __init__
    self.ctx = self.library.rwkv_init_from_file(model_path, thread_count)
  File "C:\Users\micro\Downloads\rwkv.cpp\rwkv\rwkv_cpp_shared_library.py", line 74, in rwkv_init_from_file
    ptr = self.library.rwkv_init_from_file(model_file_path.encode('utf-8'), ctypes.c_uint32(thread_count))
OSError: exception: access violation writing 0x0000000000000038
```

**Comment by bennmann** [comment]
same issue for me, i suspect the tokenizer needs some sort of conversion too(?)

**Comment by saharNooby** [comment]
Hi! Known issue: https://github.com/saharNooby/rwkv.cpp/issues/8
